### ISSUE TITLE
Create a new branch!

### ISSUE THREAD

**Issue by sahillangoo** [haideralipunjabi/covid19kashmir#16]
Create a new branch where i can push code without conflicts!

**Comment by haideralipunjabi** [comment]
If you push code into your own repo it won't conflict, why do you need a branch?

**Comment by sahillangoo** [comment]
Everyone will work on that branch then we will merge it to main branch !

**Comment by wahdatjan** [comment]
provide API

**Comment by haideralipunjabi** [comment]
> provide API

We don't have an API. We are using Google Sheets as backend.

**Comment by haideralipunjabi** [comment]
> Everyone will work on that branch then we will merge it to main branch !

Even if I have a branch on this repo, people will still need to work at their own forks. If you work at a secondary branch in a fork of this repo, I will need to first merge it to the secondary branch of my repo and then merge that branch to main branch. It's best to work on forks of main branch only.

**Comment by wahdatjan** [comment]
can you provide the link of sheet ?

**Comment by haideralipunjabi** [comment]
https://docs.google.com/spreadsheets/d/e/2PACX-1vSg-doiJ59mWF5UiJP-tCB6XCqahr9YaXe6eHiyWFyjylHtGRuy5yZrw1ZNWq3etbbyU8Gqz0i5gANp/pubhtml?gid=0&single=true

**Comment by wahdatjan** [comment]
what is its sheet name ?
who is updating the sheet?

**Comment by sahillangoo** [comment]
Cool ,
Close this issue now!

**Comment by wahdatjan** [comment]
Can you tell me the name of the sheet it is not visible??
