### ISSUE TITLE
Add folder for maintaining updates data in csv format. 

### ISSUE THREAD

**Issue by zairahms** [haideralipunjabi/covid19kashmir#25]
Hey Guys! 

Thank you so much for this initiative. You all have done a phenomenal job in such a short span of time. I am trying to use your data to do some analysis and it would be really helpful if there's a way to maintain an updated CSV file in your repository. 

Here's an example of how Johns Hopkins Univ is maintaining one, and the researchers are then able to pull this data using their GitHub URL. 

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

**Comment by haideralipunjabi** [comment]
I am planning to make some changes to how we access our data. After that is done, I will look into this as well.

**Comment by haideralipunjabi** [comment]
Media Bulletin Data is being stored at https://github.com/haideralipunjabi/covidkashmir-mediabulletins
