### ISSUE TITLE
Hospital bed stats- record and visualisation 

### ISSUE THREAD

**Issue by test2a** [haideralipunjabi/covid19kashmir#48]
Hi.
Thank you for building the big software. I have been looking for an improvement.
We already show hospital bed statistics but there is no records in data lab.
Is it possible to show historial bed records and then graph it because I have an idea that the hospital bed stats is a good indicator of the number of currently infected patients.
More beds occupied  would mean infection has started to grow

**Comment by haideralipunjabi** [comment]
Yes makes sense. It might take a while, but I will add it soon

**Comment by haideralipunjabi** [comment]
We have added the requested graphs in 9f18cb9d375c04e04d1dcdd884fe62eb04124e02
