### ISSUE TITLE
record of daily tests?

### ISSUE THREAD

**Issue by test2a** [haideralipunjabi/covid19kashmir#50]
does the data page show a record of number of new daily tests conducted ? I have been following the page for months now and i remember last week or so the tests were around 47000 but yesterdays tests showed only 31552 so if this is being done intentionally, we should have records

**Comment by haideralipunjabi** [comment]
https://covidkashmir.org/statistics

This page has a "Samples Collected" row, which shows the cumulative number of tests conducted. Subtracting the values from two consecutive days shows the daily number of tests. Social Media pages associated with this project also post an infographic daily showing the daily number of tests.

The recent drop in tests is probably due to Eid-ul-Fitr.

**Comment by test2a** [comment]
Hi. i am investigating https://www.greaterkashmir.com/news/front-page-2/no-symptoms-no-rt-pcr-test-govt/ and 
https://www.greaterkashmir.com/news/latest-news/rt-pcr-testing-labs-in-kashmir-overwhelmed-div-admin-asks-cmos-to-rationalize-covid-19-sampling/

the rationale is, if tests are being deliberately reduced and only "positive" cases are being tested, the positivity rate should have increased.  If the positivity rate remains same, which is under 10, something is amiss. 

then we have https://www.greaterkashmir.com/news/latest-news/doctors-officials-at-gmc-srinagar-associated-hospitals-barred-from-sharing-institutional-information-on-social-media/ and we have to do something.

**Comment by haideralipunjabi** [comment]
I think you should wait a few days. As I said, Eid has reduced the number of tests, and maybe the lockdown might also have some effect.

**Comment by test2a** [comment]
agreed. I was looking at vaccines available in srinagar and Jammu, srinagar, pulwama, budgam has 0 while Jammu has 9477. Interesting way to hurt people.
Lockdown is only for giving respite time for hospitals to build infrastructure which isnt happening here.
